### ISSUE TITLE
Failed to backfill error

### ISSUE THREAD

**Issue by LuisMayo** [LuisMayo/vhs-alternative-server#14]
Needs investigation. It tends to happen if you've been in a custom lobby for a while

**Comment by LuisMayo** [comment]
This error hasn't be reported in a while so I'm closing it assuming some endpoint we implemented fixed it.

May it return this issue shall be re-opened

**Comment by eXPeRi91** [comment]
The error is saying it:

**Backfilling Process**: _When a player disconnects from a match, the system attempts to find another player to fill that empty spot to ensure the game can continue smoothly. This is essential in multiplayer games to maintain the balance and flow of the match._

Server Issue, were game server or game itself(Never get a ping to a strange address) preventing them from successfully ping**(unknown address)** and/or adding Monster/New Player = (Null)

Side note: 
I am trying to work on matchmaking on my end and it happen to me like all the time 😆 (Local network)
And if I get something will create Pull Request.

**Comment by LuisMayo** [comment]
I'm working on matchmaking myself, check the `feature/matchmaking` branch if you wanna take a look or continue working from there
